### ISSUE TITLE
how about rename(give a new and better Name) for this Library ?

### ISSUE THREAD

**Issue by sgf** [marcizhu/Cereal#10]
because i found a same name Library for C++ https://github.com/USCiLab/cereal
and its has Similar functionality **(serialization)**

if this Library Keep use Cereal is not good for publicity and Promotion of the project.

and i think if write some Fast Sample Code in 1 mins on the README.md will be better help for users understands that the library usage and benefits.

The Library has c# support is a very good choice,c# suits as a server-side language.

Thank You do really good job.

**Comment by marcizhu** [comment]
I agree with you, Cereal is not a really good name. Maybe we could change it in the future. Any suggestions?

Also about a quick example in the README.md file, I think it might be a really good idea and I sure will do it as soon as possible. By the way, you can take a look at a lot of source examples in the [wiki page](https://github.com/marcizhu/Cereal/wiki). Each page explains a different object of this library, how to use it and a short fragment of code to show how it might be used. For example, you can look at how [databases](https://github.com/marcizhu/Cereal/wiki/Databases) work and see how they interact with any other class in the library.

Sorry for the late response, I've been a bit busy lately. Feel free to ask anything :D

**Comment by marcizhu** [comment]
I've updated the README.md file with a small example. I think we can close this issue now.

I'll keep thinking of a better name for this library though. If you have any other suggestion, issue or question with this library, open an issue and I'll reply as soon as possible. I'll try to be faster the next time ;)

**Comment by sgf** [comment]
Good Job!
