### ISSUE TITLE
Change windows-only functions to standard functions

### ISSUE THREAD

**Issue by marcizhu** [marcizhu/Cereal#4]
Some functions like `memcpy_s` are only available in Windows. Those should be changed to the standard C/C++ functions, and also add a macro to allow the MSVC compiler use this functions (`_CRT_SECURE_NO_WARNINGS`)

**Comment by raresica1234** [comment]
God bless

**Comment by marcizhu** [comment]
Fixed in [last commit](https://github.com/marcizhu/Cereal/commit/8c221ef59eb51251c3597bb053d81f1aeb73bddf)
